# Numerical settings (consumed by configure functor)
# Small grids for testing; paper uses 300 each
settings:
  T: 70

  # Financial asset grid
  n_a: 300
  a_min: 1.0e-08
  a_max: 10.0

  # Housing asset grid
  n_h: 300
  h_min: 1.0e-08
  h_max: 20.0

  # Total wealth grid (adjuster)
  n_w: 300
  w_min: 1.0e-08
  w_max: 30.0

  # FUES upper envelope
  m_bar: 1.1

  # Wage discretisation
  N_wage: 4

  # HD Lambda
  N_HD_LAMBDA: 1
