[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dc-smm"
version = "0.1.0a3"
description = "Fast Upper Envelope Scan (Shanker & Dobrescu, 2023)."
readme = "README.md"
requires-python = ">=3.11"

# Minimal hard runtime deps
dependencies = [
  "numpy>=1.23",
  "numba",
  "dill>=0.3.6",
  "quantecon>=0.7.2",
  "econ-ark",
  "interpolation>=0.5.2",
  "pykdtree>=1.3.12",
  # ── dynx straight from GitHub ──
  "dynx @ git+https://github.com/akshayshanker/dynx.git@main",  # pin branch/tag/commit as needed
  "scipy",
  "tabulate",
  "pyDOE",
  "ConSav",
  "EconModel"
]

[project.urls]
"Source" = "https://github.com/akshayshanker/FUES"
"Bug Tracker" = "https://github.com/akshayshanker/FUES/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dc_smm*"]       # pick up dc_smm and all its sub-packages 